// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcqQe5nxk7jbyI0WEGrCQrrw3O8mAq1o',
    appId: '1:267720438243:web:4a3b443573922d839030d6',
    messagingSenderId: '267720438243',
    projectId: 'flutter-app-d4e4e',
    authDomain: 'flutter-app-d4e4e.firebaseapp.com',
    databaseURL: 'https://flutter-app-d4e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-d4e4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHOZzYrJ7HgFC-jjgU2GI7d2yITgYeSs',
    appId: '1:267720438243:android:2311e5e0774b934f9030d6',
    messagingSenderId: '267720438243',
    projectId: 'flutter-app-d4e4e',
    databaseURL: 'https://flutter-app-d4e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-d4e4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS__ou0bZo8oHPVXTv_mx0KVuS-zs7F8c',
    appId: '1:267720438243:ios:c9e742ea5e11fef89030d6',
    messagingSenderId: '267720438243',
    projectId: 'flutter-app-d4e4e',
    databaseURL: 'https://flutter-app-d4e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-d4e4e.firebasestorage.app',
    androidClientId: '267720438243-cmk2k9k1n1tbmt2l3mo1a64640k4j60l.apps.googleusercontent.com',
    iosClientId: '267720438243-bl25r1jul2309brv15kl7hr19oar6q5f.apps.googleusercontent.com',
    iosBundleId: 'com.athr.tayser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS__ou0bZo8oHPVXTv_mx0KVuS-zs7F8c',
    appId: '1:267720438243:ios:c9e742ea5e11fef89030d6',
    messagingSenderId: '267720438243',
    projectId: 'flutter-app-d4e4e',
    databaseURL: 'https://flutter-app-d4e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-d4e4e.firebasestorage.app',
    androidClientId: '267720438243-cmk2k9k1n1tbmt2l3mo1a64640k4j60l.apps.googleusercontent.com',
    iosClientId: '267720438243-bl25r1jul2309brv15kl7hr19oar6q5f.apps.googleusercontent.com',
    iosBundleId: 'com.athr.tayser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFcqQe5nxk7jbyI0WEGrCQrrw3O8mAq1o',
    appId: '1:267720438243:web:6defd24c6b2cc85d9030d6',
    messagingSenderId: '267720438243',
    projectId: 'flutter-app-d4e4e',
    authDomain: 'flutter-app-d4e4e.firebaseapp.com',
    databaseURL: 'https://flutter-app-d4e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-d4e4e.firebasestorage.app',
  );
}
